/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import java.awt.Cursor;
import java.awt.Image;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.ResultSet;
import java.awt.image.BufferedImage;
import java.io.File;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author hp
 */
public class EndTrip extends javax.swing.JFrame {
    Connection con1 = null;
    PreparedStatement pst = null;
    ResultSet r = null;
    Client client;
    /**
     * Creates new form EndTrip
     */
    EndTrip(Client client) {
        this.client = client;
        //todo set location properly
        initComponents();
        starLabels[0] = star1Label;
        starLabels[1] = star2Label;
        starLabels[2] = star3Label;
        starLabels[3] = star4Label;
        starLabels[4] = star5Label;
        for (int i = 0; i < 5; ++i) starLabels[i].setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        try {
            yellowstarTemp = ImageIO.read(getClass().getResource("yellowstar.png"));
            greystarTemp = ImageIO.read(getClass().getResource("greystar.png"));
            yellowstar = yellowstarTemp.getScaledInstance(star1Label.getWidth(), star1Label.getHeight(), Image.SCALE_SMOOTH);
            greystar = greystarTemp.getScaledInstance(star1Label.getWidth(), star1Label.getHeight(), Image.SCALE_SMOOTH);
            star1Label.setIcon(new ImageIcon(greystar));
            star1Label.setIcon(new ImageIcon(greystar));
            star2Label.setIcon(new ImageIcon(greystar));
            star3Label.setIcon(new ImageIcon(greystar));
            star4Label.setIcon(new ImageIcon(greystar));
            star5Label.setIcon(new ImageIcon(greystar));
        } catch (Exception e) {
            e.printStackTrace();
        }
        
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        rateYourDriverLabel = new javax.swing.JLabel();
        star1Label = new javax.swing.JLabel();
        star2Label = new javax.swing.JLabel();
        star3Label = new javax.swing.JLabel();
        star4Label = new javax.swing.JLabel();
        star5Label = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        rateYourDriverLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        rateYourDriverLabel.setForeground(new java.awt.Color(240, 240, 240));
        rateYourDriverLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rateYourDriverLabel.setText("Rate Your Driver");

        star1Label.setText("jLabel1");
        star1Label.setMaximumSize(new java.awt.Dimension(30, 30));
        star1Label.setMinimumSize(new java.awt.Dimension(30, 39));
        star1Label.setPreferredSize(new java.awt.Dimension(30, 30));
        star1Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                star1LabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                star1LabelMouseEntered(evt);
            }
        });

        star2Label.setText("jLabel1");
        star2Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                star2LabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                star2LabelMouseEntered(evt);
            }
        });

        star3Label.setText("jLabel1");
        star3Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                star3LabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                star3LabelMouseEntered(evt);
            }
        });

        star4Label.setText("jLabel1");
        star4Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                star4LabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                star4LabelMouseEntered(evt);
            }
        });

        star5Label.setText("jLabel1");
        star5Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                star5LabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                star5LabelMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rateYourDriverLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(star1Label, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(star2Label, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(star3Label, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(star4Label, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(star5Label, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rateYourDriverLabel)
                .addGap(62, 62, 62)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(star1Label, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(star2Label, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(star3Label, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(star4Label, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(star5Label, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(171, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void setAllStarsToGrey() {
        for (int i = 0; i < 5; ++i) {
            starLabels[i].setIcon(new ImageIcon(greystar));
        }
    }
    
    private void setSelectedStarsToYellow(int n) {
        for (int i = 0; i < n; ++i) {
            starLabels[i].setIcon(new ImageIcon(yellowstar));
        }
    }
    
    private void redistributeDrivers(Connection conn) throws SQLException{
        //redistributes free driver with 20% probablity
        String query = "UPDATE cab SET location = FLOOR(1 + RAND() * 27) where inService = 0 and RAND()<0.2;";
        pst = conn.prepareStatement(query);
        pst.executeUpdate();
    }
    
    private void updateRatingAndFreeDriver(int currentTripRating) {
        JOptionPane.showMessageDialog(null, "Rs " + Cab.cost + " have been deducted from your wallet.");
        client.wallet -= Cab.cost;
         try{
            String query = "UPDATE `logindatabase` SET `wallet` = ? WHERE `logindatabase`.`Username` = ?;";
            con1 = DatabaseDetails.establishConnection();
            pst = con1.prepareStatement(query);
            pst.setInt(1, client.wallet);
            pst.setString(2, client.username);
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Updated Wallet Balance: " + client.wallet);
            query = "UPDATE cab SET InService = 0, Location = ?, completedTrips = completedTrips + 1, rating = (rating * completedTrips + ?)/(completedTrips + 1) WHERE cab.driverName = ?;";
            pst = con1.prepareStatement(query);
            pst.setInt(1, Cab.destination);
            pst.setInt(2, currentTripRating);
            pst.setString(3, Cab.driverName);
            pst.executeUpdate();
            Cab.pickup = Cab.destination;
            redistributeDrivers(con1);
            this.setVisible(false);
            
        } catch (Exception e) {
        e.printStackTrace();
        }
    }
    
    private void star1LabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_star1LabelMouseEntered
        setAllStarsToGrey();
        setSelectedStarsToYellow(1);
        
    }//GEN-LAST:event_star1LabelMouseEntered

    private void star2LabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_star2LabelMouseEntered
        setAllStarsToGrey();
        setSelectedStarsToYellow(2);
    }//GEN-LAST:event_star2LabelMouseEntered

    private void star3LabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_star3LabelMouseEntered
        setAllStarsToGrey();
        setSelectedStarsToYellow(3);
    }//GEN-LAST:event_star3LabelMouseEntered

    private void star4LabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_star4LabelMouseEntered
        setAllStarsToGrey();
        setSelectedStarsToYellow(4);
    }//GEN-LAST:event_star4LabelMouseEntered

    private void star5LabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_star5LabelMouseEntered
        setAllStarsToGrey();
        setSelectedStarsToYellow(5);
    }//GEN-LAST:event_star5LabelMouseEntered

    private void star1LabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_star1LabelMouseClicked
        updateRatingAndFreeDriver(1);
    }//GEN-LAST:event_star1LabelMouseClicked

    private void star2LabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_star2LabelMouseClicked
        updateRatingAndFreeDriver(2);

    }//GEN-LAST:event_star2LabelMouseClicked

    private void star3LabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_star3LabelMouseClicked
        updateRatingAndFreeDriver(3);
    }//GEN-LAST:event_star3LabelMouseClicked

    private void star4LabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_star4LabelMouseClicked
        updateRatingAndFreeDriver(4);
    }//GEN-LAST:event_star4LabelMouseClicked

    private void star5LabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_star5LabelMouseClicked
        updateRatingAndFreeDriver(5);
    }//GEN-LAST:event_star5LabelMouseClicked
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EndTrip.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EndTrip.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EndTrip.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EndTrip.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel rateYourDriverLabel;
    private javax.swing.JLabel star1Label;
    private javax.swing.JLabel star2Label;
    private javax.swing.JLabel star3Label;
    private javax.swing.JLabel star4Label;
    private javax.swing.JLabel star5Label;
    // End of variables declaration//GEN-END:variables
    private BufferedImage yellowstarTemp, greystarTemp;
    Image yellowstar, greystar;
    private JLabel[] starLabels = new JLabel[5];
}
